### ISSUE TITLE
arxiv-vanity renders an old version of paper, instead of the latest version

### ISSUE THREAD

**Issue by wenyong-h** [arxiv-vanity/arxiv-vanity#343] opened 2018-11-25 06:07 UTC
You can test with this link
https://arxiv.org/pdf/1709.02755.pdf
The latest version's tiltle is  _Simple Recurrent Units for Highly Parallelizable Recurrence_ .
But arxiv-vanity still renders the old one with title _Training RNNs as Fast as CNNs_

**Comment by bfirsh** [comment] 2019-03-27 11:38
Dupe of #374. Thanks for the report!

**Closed by bfirsh** 2019-03-27 11:38 UTC
