### ISSUE TITLE
Maybe Integrating annotatorjs?

### ISSUE THREAD

**Issue by 0bserver07** [arxiv-vanity/arxiv-vanity#73] opened 2017-10-24 03:10 UTC
I'm currently building a similar project for fun, but without the actual papers. The goal is to allow reviewers annotate and add comments to the Paper's review.

Though, since you already have the website laid out, [annotatorjs](http://annotatorjs.org/) might come in handy as well to integrate.

This is one of the open-implementations of the library that can be integrated (https://web.hypothes.is/)

**Comment by bfirsh** [comment] 2017-10-26 09:14
Dupe of #70. Thanks for the suggestion!

**Closed by bfirsh** 2017-10-26 09:14 UTC
